### ISSUE TITLE
compilation errors on catalina-xcode

### ISSUE THREAD

**Issue by tlambert03** [cirruslabs/osx-images#21]
I'm not exactly sure what's happening here, but we're seeing C-compilation errors (unable to find libcpp.algorithm) on the new `catalina-xcode` container that we did not see on mojave.  

```shell
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the 
command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc:29:10: fatal error: 
'algorithm' file not found
#include <algorithm>
```
(full task here https://cirrus-ci.com/task/6660339609632768?command=pip#L387-L455)

This occurs while building [numcodecs](https://github.com/zarr-developers/numcodecs) on mac, but only with python 3.6, so I assume their sdist may also be playing a role here?  or perhaps its the only one in our dependencies that exposes the issue.

this _should_ be sufficient to replicate:
```yaml
task:
  name: macos 3.6 catalina
  osx_instance:
    image: catalina-xcode
  setup_script:
    - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > install.sh
    - bash install.sh -b -p $HOME/conda
    - conda install --yes -c conda-forge setuptools
    - conda install -yn base conda=4.8.1  # 4.8.2 completely breaks py3.6 at the moment
    - conda install -y python=3.6
    - pip install zarr
```

I am trying to fix this on my own, maybe by adding something to `includes`?  but figured I would mention it in case there is a more general catalina thing that might be useful to include by default in the osx container...  thanks.
